########################################
# CONSTANTS
########################################
uint8 SNAPANDROTATE=0 # mode: rotate, stop, snapshot, rotate, stop, snapshot, ...
uint8 CONTINUOUS=1    # mode: keep rotating while taking snapshots
uint8 STOP=2          # mode: stop an ongoing panorama creation

uint8 STARTED=0       # status
uint8 IN_PROGRESS=1   # status
uint8 STOPPED=2       # status

########################################
# Messages
########################################
uint8 mode            # mode for taking the pictures
float32 pano_angle    # total angle of panorama picture
float32 snap_interval # angle interval when creating the panorama picture in snap&rotate mode, time interval otherwise 
float32 rot_vel       # rotating velocity
---
uint8 status
